### ISSUE TITLE
Improve message lightbox. 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/loklak_search#105]
Currently the link area of a tweet opens the actual tweet at twitter. The expected behavior would rather be to open a lightbox (just like twitter), that brings the user back to the search page.

* [x] Please implement a simple overlay lightbox with the tweet info
* [x] Autolinking the text in the cards #141.
* [ ] Responsive UI design of message lightbox #142.
* [ ] In the bottom area show a link with "View at Twitter" (This should be generic, e.g. as we are adding YouTube this should show "View at YouTube" if the source is YouTube)

![screenshot from 2016-11-04 03 39 49](https://cloud.githubusercontent.com/assets/1583873/19982551/760e6022-a241-11e6-92ca-70ed511de47d.png)

**Comment by Heredroky** [comment]
@mariobehling Can I work on this issue?

**Comment by hemantjadon** [comment]
Yes @Heredroky sure go ahead.

**Comment by rishiraj824** [comment]
If this issue is still not fixed, can I do it ? @Heredroky

**Comment by Heredroky** [comment]
Sorry, I'm working on it

**Comment by rishiraj824** [comment]
No Problem :)

**Comment by hemantjadon** [comment]
The above PR #137 implements a basic design which can be improved.

Also the performance can be improved a lot by using a single component for overlay with `State` based selection. Which will be much easier to implement than the current architecture.

**Comment by Achint08** [comment]
@hemantjadon what new design features can be added in the box? I recently found a issue #141 .
I would like to work on this issue. Can I?

**Comment by hemantjadon** [comment]
@Achint08  Yes sure you can go ahead and work on this.

* [ ] Responsive UI design of message lightbox #142.

* [ ] Autolinking the text in the cards #141.

**Comment by hemantjadon** [comment]
For auto linking use `AutolinkerConfig` and `feed-autolinker` component. take hint from what is implemented in `feed-card`. It is easy to implement.

**Comment by rishiraj824** [comment]
Can I work on the responsiveness of the Lightbox? @hemantjadon

**Comment by Achint08** [comment]
I was implementing this lighbox as a single component for overlay with State based selection. Almost done with it. So to take advantage of this reducer state , What I am thinking is to add a left and right arrow button so that user can scroll the tweets in the lightbox format only(something like slide effect). What about this @mariobehling @hemantjadon @jig08 ?

**Comment by hemantjadon** [comment]
This can be a later improvement I think, not required right now
